POST http://localhost:5000/api/query
Content-Type: application/json

{
    "queryData":"r"
}

###
POST http://localhost:5000/api/add
Content-Type: application/json

{
    "shortForm":"RSI",
    "fullForm":"silicon rectifier"
}


