POST http://localhost:5000/abbrserver/api/query
Content-Type: application/json

{
    "queryData":"r"
}

###
POST http://localhost:5000/abbrserver/api/add
Content-Type: application/json

{
    "shortForm":"CP",
    "fullForm":"Compressor"
}

###
POST https://abbrserver.herokuapp.com/abbrserver/api/query
Content-Type: application/json

{
    "queryData":"c"
}
