POST http://localhost:9000/.netlify/functions/server/query
Content-Type: application/json

{
    "queryData":"cp"
}

###
POST http://localhost:9000/.netlify/functions/server/add
Content-Type: application/json

{
    "shortForm":"BP",
    "fullForm":"Brake Pressure"
}